name: betogether
description: BeTogether - An app to keep in touch with the world when you are by yourself.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  amazon_cognito_identity_dart_2: ^0.1.12+2
  shared_preferences: "^0.4.1"
  flushbar: ^1.10.0
  rounded_loading_button: ^1.0.0
  http: "0.12.0+4"
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  flutter_form_builder:

dev_dependencies:
  test:  "1.14.2"
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/img/deportes.jpg
    - assets/img/yoga.jpg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
